name: Testing
permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Run unit tests
    runs-on: self-hosted

    steps:
      - name: Clean workspace
        run: |
          sudo rm -rf ${{ github.workspace }}/* || true
          sudo rm -rf ${{ github.workspace }}/.* || true

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libgtk-4-dev \
            libssl-dev \
            libgtk4-layer-shell-dev \
            pandoc \
            groff

      - name: Run cargo check
        run: cargo check --all-targets

      - name: Run tests
        run: cargo test --all-features --no-fail-fast -- --nocapture

      - name: Verify formatting
        run: cargo fmt --all -- --check

      - name: Lint with clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
